language: android
sudo: false
android:
  components:
  - platform-tools
  - tools
  - build-tools-21.1.1
  - build-tools-22.0.1
  - android-22
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-21
  - sys-img-armeabi-v7a-android-21
jdk:
- oraclejdk8

cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/2.3

before_script:
#  - "echo $JAVA_OPTS"
  - export JAVA_OPTS=-Xmx4096m #TODO: REMOVE THESE LINES
  - export GRADLE_OPTS="-Xmx4096m -XX:MaxPermSize=4096m"
  - chmod +x gradlew
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - ls -R
script:
  - "./gradlew testRelease --stacktrace"
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - "./gradlew connectedAndroidTest --stacktrace"
  - if [ "$TRAVIS_BRANCH" = "alpha" ]; then ./gradlew appengineUpdate; fi
  - if [ "$TRAVIS_BRANCH" = "alpha" ]; then ./gradlew publishRelease; fi
after_success:
  - git config user.email $GIT_EMAIL
  - git config user.name $GIT_NAME
  - git commit -a -m "Committed by Travis-CI for updated versioncodes"
  - if [ "$TRAVIS_BRANCH" = "alpha" ]; then git push https://$GIT_CREDS@github.com/tokko/Recipesv2.git HEAD:master; fi
dd:
  secure: oNUiykroCyjutmxvAbEOJtYx7Saknbo0GENkeqoHulpLccwT8UudUzCS2i+aUqxZh3bPyR3Hmki2Bwf1nSdlvTmTs7RC33Xrizlbl4Wky5A1yUQlgLdpofnDfE2/PQiLBB8SJB0ZMf0y1FjqHPIkDEKnRaUVctM/Pfs0GzDaoERRJWS8hFAej2KslybiV4Lxnecy53Elh1Tj2vTYCDdP6eyG2nMy5usL3/I3k0J+yHK6NTTcgIF8A8osuY4VMQuoEVRDbV/ejNwvLeN4GNeQxUw3mUCCDQ5Vt+uKgCs0qYeU1+LEzSq3iTavv4P11LKmI2nICTvyN/zEucqPD8Rh+r8f8Cci25qF2PQ/OVFSh36zdaUxIy8iV3f8fo+O0/8IKd00CAJapCVU+ZkXKuFjlNie4MN3mN027M8cQJ9VPnD9m7ZouHhLPE4un2k9KzMP97sTpTLZPddA4vUrqZewSziKF+9Ps/t7PSZibIwzN1H8+HaVGE7bFH79LYC18MM3ZxQM0yZwANp1dhkyUbaPzBIs22m4sbhCEsv+P3rHl4ZgxSvaeVWCEsI1SH+EAVDVJGyM4imderoMRMmliN1uLP2nSrlQD/bxg+gnalUFt4cKqYaAAunxOrko7o0RAizCNDYNiR9TAyifLRIp4c79E64LmSeWtjNC/0Z/jqbO5x0=
